type AddProjectStatus @embedded {
  id: String!
  success: Boolean!
}

type EditProjectStatus @embedded {
  success: Boolean!
  nModified: Float!
}

type Project @collection(name: "projects") {
  id: ID!
  user: String!
  name: String!
  isPublic: Boolean!
  description: String
  projectJson: String
  lastModified: DateTime!
}

type Query {
  project(id: String!): Project @resolver(name: "get_project")
  projects: [Project!]! @resolver(name: "get_projects")
  getProjectsByUser(user: String!): [Project!]!
    @resolver(name: "get_projects_by_user")
}

type Mutation {
  addProject(
    user: String!
    name: String!
    isPublic: Boolean!
    description: String
    projectJson: String
  ): AddProjectStatus! @resolver(name: "add_project")
  editProject(
    name: Strings
    description: String
    isPublic: Boolean
    projectJson: String
    id: String!
  ): EditProjectStatus! @resolver(name: "edit_project")
  removeProject(id: String!): EditProjectStatus!
    @resolver(name: "remove_project")
}
