type Project @collection(name: "projects") {
  user: String!
  name: String!
  isPublic: Boolean!
  description: String
  projectJson: String
}

type Query {
  getProjectsByUser(user: String!): [Project!]!
    @resolver(name: "get_projects_by_user", paginated: true)
}
